name: Update Orders

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Download CSV
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/1q4GA6nKhfwEqMb0uVlDT8QxgovqucAG1C_d3BDaYeG4/export?format=csv" -o orders.csv
     
      - name: Ensure state file exists
        run: |
         if [ ! -f previous_orders.json ]; then
         echo "{}" > previous_orders.json
         fi
    
      - name: Generate Smart Report
        run: node generate.js

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .
          git commit -m "Auto update orders" || exit 0
          git push

      - name: Telegram Notification
        shell: bash
        run: |
          if [ ! -f report.json ]; then
            echo "report.json missing"
            exit 0
          fi

          REPORT=$(cat report.json)

          NEW=$(echo "$REPORT" | jq '.newCount')
          CHANGED=$(echo "$REPORT" | jq '.changedCount')

          DATE=$(date '+%d-%b-%Y')

          if [ "$NEW" -eq 0 ] && [ "$CHANGED" -eq 0 ]; then
            TEXT="🚀 Smart Orders Report
          📅 Date: $DATE

          ✅ No updates today
          All apps are up to date."
          else
            NEW_LIST=$(node -e "
          const r = require('./report.json');
          r.newApps.forEach(a => {
            console.log('🆕 ' + a.id.split('-')[1] + ' - ' + a.app + ' - ' + a.startDate);
          });
          ")

          CHANGED_LIST=$(node -e "
          const r = require('./report.json');
          r.changedApps.forEach(a => {
            console.log('✏️ ' + a.id.split('-')[1] + ' - ' + a.newRecord.app);
          });
          ")

            FORMATTED_NEW=$(echo "$NEW_LIST" | sed 's/^/🆕 /')
            FORMATTED_CHANGED=$(echo "$CHANGED_LIST" | sed 's/^/✏️ /')

            TEXT="🚀 Smart Orders Report
          📅 Date: $DATE

          🆕 New Apps: $NEW
          ✏️ Changed Apps: $CHANGED

          ──────────────

          🆕 New Apps List
          $FORMATTED_NEW

          ──────────────

          ✏️ Changed Apps List
          $FORMATTED_CHANGED"
          fi

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="$TEXT"

      - name: Failure Notification
        if: failure()
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="❌ Orders Update Failed! Check logs."
